name: drone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  socket_io_client: ^2.0.3+1
  webview_flutter: ^4.8.0
  flutter_joystick: ^0.2.2
  logging: ^1.2.0
  image: ^4.5.4
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  camera: ^0.11.1
  permission_handler: ^11.3.1
  flutter_map: ^8.2.1
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.6.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/drone.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/drone.jpg
    - assets/image/plane.png
    - assets/lottie/droneFly.json