name: drone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  webview_flutter: ^4.8.0
  flutter_joystick: ^0.2.2
  logging: ^1.2.0
  image: ^4.5.4
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/drone.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/drone.jpg
    - assets/lottie/droneFly.json